site_name: ttkbootstrap
repo_url: https://github.com/israel-dryer/ttkbootstrap
repo_name: israel-dryer/ttkbootstrap

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
  icon:
    logo: material/view-dashboard

plugins:
  - search
  - mkdocstrings:
      handlers:
          python:
              setup_commands:
                - import sys
                - sys.path.append("src")

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.snippets

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/israel-dryer/ttkbootstrap
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/IDryer

nav:
  - Home: 
    - index.md
    - about.md
    - changelog.md
    - license.md
  - 'Getting started':
    - gettingstarted/installation.md
    - gettingstarted/tutorial.md
    - gettingstarted/legacy.md
  - 'Style guide':
    - styleguide/index.md
    - styleguide/button.md
    - styleguide/checkbutton.md
    - styleguide/combobox.md
    - styleguide/dateentry.md
    - styleguide/datepickerpopup.md
    - styleguide/entry.md
    - styleguide/floodgauge.md
    - styleguide/frame.md
    - styleguide/label.md
    - styleguide/labelframe.md
    - styleguide/menubutton.md
    - styleguide/meter.md
    - styleguide/notebook.md
    - styleguide/panedwindow.md
    - styleguide/progressbar.md
    - styleguide/radiobutton.md
    - styleguide/scale.md
    - styleguide/scrollbar.md
    - styleguide/separator.md
    - styleguide/sizegrip.md
    - styleguide/spinbox.md
    - styleguide/treeview.md
    - styleguide/legacywidgets.md
  - API: 
    - api/index.md
    - 'dialogs module':
      - api/dialogs/dialog.md
      - api/dialogs/messagedialog.md
      - api/dialogs/querydialog.md
      - api/dialogs/datepickerdialog.md
      - api/dialogs/fontdialog.md
      - api/dialogs/messagebox.md
      - api/dialogs/querybox.md
    - 'icons module':
      - api/icons/emoji.md
      - api/icons/icon.md
    - 'scrolled module':
      - api/scrolled/scrolledframe.md
      - api/scrolled/scrolledtext.md
    - 'style module': 
      - api/style/bootstyle.md
      - api/style/colors.md
      - api/style/style.md
      - api/style/stylebuildertk.md
      - api/style/stylebuilderttk.md
      - api/style/themedefinition.md    
    - 'toast module': api/toast.md
    - 'tooltip module': api/tooltip.md
    - 'utility module': api/utility.md
    - 'widgets module':
      - api/widgets/dateentry.md
      - api/widgets/floodgauge.md
      - api/widgets/meter.md
    - 'window module':
      - api/window/window.md
      - api/window/toplevel.md
  - Themes:
    - themes/index.md
    - themes/light.md
    - themes/dark.md
    - themes/definitions.md
    - themes/themecreator.md
  - Gallery:
    - gallery/index.md
    - gallery/calculator.md
    - gallery/collapsingframe.md
    - gallery/dataentry.md
    - gallery/equalizer.md
    - gallery/filebackup.md
    - gallery/filesearchengine.md
    - gallery/magicmouse.md
    - gallery/mediaplayer.md
    - gallery/pccleaner.md
    - gallery/stopwatch.md
    - gallery/textreader.md
  - Cookbook: 
    - cookbook/index.md
    - cookbook/gif-animation.md
    - cookbook/validate-user-input.md
